### ISSUE TITLE
Action doesn't use gokhlayeh/textidote 

### ISSUE THREAD

**Issue by marcosrmartin** [ChiefGokhlayeh/textidote-action#51]
Every time that an action is thrown, it runs the Dockerfile to build the image (executing all the commands and installing all the dependencies), instead of using the Docker image, which is already built and ready to use.

It takes 1 and a half minutes, every time you exec the action.
![image](https://user-images.githubusercontent.com/75510647/225373503-a51894f4-9774-4c98-b3aa-508e26a9692e.png)

**Comment by ChiefGokhlayeh** [comment]
I see how that might be an inconvenience.

This action builds the image from its `Dockerfile` as described [here](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action). If anything, I would have hoped GitHub cached the action internally. Apparently they don't.

Switching [this line](https://github.com/ChiefGokhlayeh/textidote-action/blob/18d93c5e98921abfc6217d16ddab9260e29a74d7/action.yml#L28) in `action.yaml` may provide the desired effect, however, this repo also runs some self-tests to ensure the action is functional _before_ it is being pushed to Docker Hub (e.g. [here](https://github.com/ChiefGokhlayeh/textidote-action/blob/18d93c5e98921abfc6217d16ddab9260e29a74d7/.github/workflows/test.yml#L11-L17)). If there is a way to run the tests _before_ pushing anything to Docker Hub **and** having the `action.yaml` reference a tested Docker Hub image, I'd gladly accept it as a PR.
