### ISSUE TITLE
DOCKERHUB_PASSWORD usage

### ISSUE THREAD

**Issue by marcosrmartin** [ChiefGokhlayeh/textidote-action#52]
Now, the API supports DOCKERHUB_TOKEN, use it instead of DOCKERHUB_PASSWORD.

![image](https://user-images.githubusercontent.com/75510647/225465466-5695c74c-6efb-45c8-abaa-ad218f0a1900.png)

**Comment by ChiefGokhlayeh** [comment]
Used to be an issue with [peter-evans/dockerhub-description](https://github.com/peter-evans/dockerhub-description/tree/v3.0.0) up until version incl. v3.0.0.

Thanks for fixing.
